#!/usr/bin/python
#
# Code lifted from
# http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
#
import sys
from passlib.hash import sha512_crypt

if (len(sys.argv) == 2):
    print sha512_crypt.using(rounds=5000).hash(sys.argv[1])
else:
    print >> sys.stderr, "Usage:", sys.argv[0], "password-to-encrypt"
    sys.exit(1)
